---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
install:
  - sudo apt update
  - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
  - curl -fsSL http://bit.ly/install_pkg | PKG="vagrant bridge-utils dnsmasq ebtables libvirt qemu-kvm ruby-devel gcc" bash
  - vagrant plugin install vagrant-libvirt
  - vagrant plugin install vagrant-reload
script:
  - sudo -E vagrant up $VAGRANT_NAME
env:
  - PROVIDER=libvirt CREATE_SRIOV_VFS=true CREATE_QAT_VFS=true VAGRANT_NAME=ubuntu_bionic_libvirt
  - PROVIDER=virtualbox VAGRANT_NAME=ubuntu_bionic_virtualbox
  - PROVIDER=libvirt CREATE_SRIOV_VFS=true CREATE_QAT_VFS=true VAGRANT_NAME=centos_7_libvirt
  - PROVIDER=virtualbox VAGRANT_NAME=centos_7_virtualbox
  - PROVIDER=libvirt VAGRANT_NAME=opensuse_libvirt
  - PROVIDER=virtualbox VAGRANT_NAME=opensuse_virtualbox
