---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
before_install:
  - if [ -n "${VAGRANT_EXECUTION:-}" ]; then sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu ; fi
  - if [ -n "${VAGRANT_EXECUTION:-}" ]; then curl -fsSL http://bit.ly/install_pkg | PKG="vagrant bridge-utils dnsmasq ebtables libvirt qemu-kvm ruby-devel gcc" bash ; fi
  - if [ -n "${VAGRANT_EXECUTION:-}" ]; then vagrant plugin install vagrant-libvirt; fi
  - if [ -n "${VAGRANT_EXECUTION:-}" ]; then vagrant plugin install vagrant-reload; fi
jobs:
  include:
    - name: Lint validation
      language: python
      install:
        - pip install tox
      script:
        - tox -e lint
        - shellcheck -x *.sh
    - name: Validating Bare Metal installation
      script:
        - PROVIDER=libvirt ./setup.sh
    - name: Ubuntu 18.04 LTS validation using Libvirt provider
      script:
        - PROVIDER=libvirt sudo -E vagrant up ubuntu_bionic_libvirt
      env:
        - VAGRANT_EXECUTION=true
    - name: Ubuntu 18.04 LTS validation using VirtualBox provider
      script:
        - PROVIDER=virtualbox sudo -E vagrant up ubuntu_bionic_virtualbox
      env:
        - VAGRANT_EXECUTION=true
    - name: CentOS 7 validation using Libvirt provider
      script:
        - PROVIDER=libvirt sudo -E vagrant up centos_7_libvirt
      env:
        - VAGRANT_EXECUTION=true
    - name: CentOS 7 validation using VirtualBox provider
      script:
        - PROVIDER=virtualbox sudo -E vagrant up centos_7_virtualbox
      env:
        - VAGRANT_EXECUTION=true
