---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Vagrant setup

inputs:
  distro:
    description: Linux distribution
    default: ubuntu_focal

runs:
  using: "composite"
  steps:
    - name: Cache Vagrant boxes
      uses: actions/cache@v3.0.10
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ inputs.distro }}-${{ hashFiles('distros_supported.yml') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-${{ inputs.distro }}-
          ${{ runner.os }}-vagrant-${{ hashFiles('distros_supported.yml') }}
    - name: Apply workaround for VBoxHeadless issue on macOS (https://www.virtualbox.org/ticket/20636)
      shell: bash
      run: |
        if [[ "$(VBoxManage --version)" == "6.1.28r147628" ]]; then
            find . -type f -name "Vagrantfile" -exec sed -i 's|v.gui = .*|v.gui = true|g' {} \;
        fi
    - name: Install Vagrant Reload plugin
      shell: bash
      run: vagrant plugin install vagrant-reload
